# Spiral Dynamics Optimization

In [202]:
import numpy as np
import math
import random
import pandas as pd

In [263]:
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  5 21:32:53 2018

@author: YorozuyaSaint
"""

def mat_R_ij(dim, i, j, theta):
    c, s = np.cos(np.deg2rad(theta)), np.sin(np.deg2rad(theta))
    R = np.zeros((dim, dim))
    for a in range(dim):
        for b in range(dim):
            if ((a==i) and (b==i)) or ((a==j) and (b==j)):
                R[a][b] = c
            elif ((a==j) and (b==i)):
                R[a][b] = s
            elif ((a==i) and (b==j)):
                R[a][b] = -s
            else:
                if(a==b):
                    R[a][b] = 1
                else :
                    R[a][b] = 0
    return R


def transformation_matrix(mat_R_ij, dim, r, theta):
    '''
    generate the matrix of S(n) = r(n)*R(n), where r = contraction matrix, R = rotation matrix
    '''
    # generate r matrix
    mat_r = np.zeros((dim,dim))
    for i in range(dim):
        for j in range(dim):
            if i==j:
                mat_r[i][j]=r
                    
    # generate R(n) matrix
    mat_Rn = np.zeros((dim, dim))
    c, s = np.cos(np.deg2rad(theta)), np.sin(np.deg2rad(theta))
    if(dim<2):
        print("Dimension is not viable !!")
    elif(dim>=2):
        R=np.identity(dim)
        for i in range(dim-1):
            for j in range(i):
                R=np.matmul(R, mat_R_ij(dim, i,j, theta))
        mat_Rn = R
    # S(n) = r(n)*R(n)
    return np.matmul(mat_r, mat_Rn)


def spiral_dynamics_optimization(F, S, R, m, theta, r, kmax, x_dim, domain, log=True):
    '''
    Function F optimization using spiral dynamics -> rotating & contracting points
    '''
    if log:
        print("Init points = ",m)
        print("Theta = ",theta)
        print("r = ",r)
        print("iter_max = ",kmax)
        print("dimension = ",x_dim)
        print("domain = ",domain)
        print()
    
    # generate m init points using random uniform between function domain
    x = np.array([[random.uniform(domain[0], domain[1]) for j in range(x_dim)] for i in range(n)])
    f = np.array([F(x_) for x_ in x])

    # search the minimum/maximum (depends on the problem) of f(init_point), in this case, max
    f_x_star = np.max(f)
    x_star = x[np.argmax(f)]
    
    # rotation function
    rotate_point = lambda x, x_star : np.matmul( S(R, x_dim, r, theta), x ) - np.matmul( ( S(R, x_dim, r, theta) - np.identity(x_dim) ), x_star )
        
    # rotate the points
    for k in range(kmax):
        x = np.array([rotate_point(x[i], x_star) for i in range(len(x))])
        f = np.array([F(x_) for x_ in x])
        x_star_next = x[np.argmax(f)]
        if(F(x_star_next) > F(x_star)):
            x_star = np.copy(x_star_next)
        if log:
            print("Iteration\tx_star\tF(x_star)")
            print(str(k)+" "+str(x_star)+" "+str(F(x_star)))
    return x_star, F(x_star)

In [264]:
# R3(1,3)
print(mat_R_ij(3,0,2, 90))


[[ 6.123234e-17  0.000000e+00 -1.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00]
 [ 1.000000e+00  0.000000e+00  6.123234e-17]]


$$F(x)=\frac{1}{1+ \sum_{i=1}^{n} |f_i(x)|}
$$

$$f(x_1, x_2)=\frac{1}{2}(x_1^4-16x_1^2+5x_1) + \frac{1}{2}(x_2^4-16x_2^2+5x_2) \\
-4\leq x_1,x_2\leq4
$$

In [265]:
# try the function above
# seed the random, as usual, to create reproducible result
random.seed(9295)
# dimension of x, could also be dim=2 (example), your choice
x=np.array([0,0])
domain=np.array([-4,4])
f=[lambda x : ( (x[0]**4) - 16*(x[0]**2) + 5*x[0] )/2 + ( x[1]**4 - 16*(x[1]**2) + 5*x[1] )/2]
#transform f(x) into maximization function
F = lambda x : 1/( 1 + sum([abs(f_(x)) for f_ in f]) )

x_star, F_x_star = spiral_dynamics_optimization(F, transformation_matrix, mat_R_ij, 20, 30, 0.9, 350, len(x), domain)
print("\nFinal value of x, F(x) is : ",x_star,",",F_x_star,"")





Init points =  20
Theta =  30
r =  0.9
iter_max =  350
dimension =  2
domain =  [-4  4]

Iteration	x_star	F(x_star)
0 [0.54916294 0.11714945] 0.552156399111173
Iteration	x_star	F(x_star)
1 [0.54916294 0.11714945] 0.552156399111173
Iteration	x_star	F(x_star)
2 [0.54916294 0.11714945] 0.552156399111173
Iteration	x_star	F(x_star)
3 [0.54916294 0.11714945] 0.552156399111173
Iteration	x_star	F(x_star)
4 [0.54916294 0.11714945] 0.552156399111173
Iteration	x_star	F(x_star)
5 [0.54916294 0.11714945] 0.552156399111173
Iteration	x_star	F(x_star)
6 [0.54916294 0.11714945] 0.552156399111173
Iteration	x_star	F(x_star)
7 [0.54916294 0.11714945] 0.552156399111173
Iteration	x_star	F(x_star)
8 [0.54916294 0.11714945] 0.552156399111173
Iteration	x_star	F(x_star)
9 [0.54916294 0.11714945] 0.552156399111173
Iteration	x_star	F(x_star)
10 [-0.17825475  0.33097878] 0.5739676446252171
Iteration	x_star	F(x_star)
11 [0.47642117 0.13853239] 0.7112276912754054
Iteration	x_star	F(x_star)
12 [-0.11278715  0.3117341

Iteration	x_star	F(x_star)
149 [0.37801078 0.12555881] 0.9999999855376482
Iteration	x_star	F(x_star)
150 [0.37801078 0.12555881] 0.9999999855376482
Iteration	x_star	F(x_star)
151 [0.37801076 0.12555864] 0.9999999881966507
Iteration	x_star	F(x_star)
152 [0.37801076 0.12555864] 0.9999999881966507
Iteration	x_star	F(x_star)
153 [0.37801078 0.12555878] 0.9999999905280942
Iteration	x_star	F(x_star)
154 [0.37801078 0.12555878] 0.9999999905280942
Iteration	x_star	F(x_star)
155 [0.37801076 0.12555867] 0.9999999922389738
Iteration	x_star	F(x_star)
156 [0.37801077 0.12555877] 0.9999999922513781
Iteration	x_star	F(x_star)
157 [0.37801077 0.12555868] 0.9999999937899462
Iteration	x_star	F(x_star)
158 [0.37801077 0.12555868] 0.9999999937899462
Iteration	x_star	F(x_star)
159 [0.37801077 0.12555875] 0.9999999949035159
Iteration	x_star	F(x_star)
160 [0.37801077 0.12555868] 0.9999999949206035
Iteration	x_star	F(x_star)
161 [0.37801077 0.12555874] 0.9999999959211006
Iteration	x_star	F(x_star)
162 [0.3780

Iteration	x_star	F(x_star)
307 [0.37801077 0.12555872] 0.9999999999999989
Iteration	x_star	F(x_star)
308 [0.37801077 0.12555872] 0.9999999999999991
Iteration	x_star	F(x_star)
309 [0.37801077 0.12555872] 0.9999999999999991
Iteration	x_star	F(x_star)
310 [0.37801077 0.12555872] 0.9999999999999991
Iteration	x_star	F(x_star)
311 [0.37801077 0.12555872] 0.9999999999999993
Iteration	x_star	F(x_star)
312 [0.37801077 0.12555872] 0.9999999999999996
Iteration	x_star	F(x_star)
313 [0.37801077 0.12555872] 0.9999999999999996
Iteration	x_star	F(x_star)
314 [0.37801077 0.12555872] 0.9999999999999998
Iteration	x_star	F(x_star)
315 [0.37801077 0.12555872] 0.9999999999999998
Iteration	x_star	F(x_star)
316 [0.37801077 0.12555872] 0.9999999999999998
Iteration	x_star	F(x_star)
317 [0.37801077 0.12555872] 0.9999999999999998
Iteration	x_star	F(x_star)
318 [0.37801077 0.12555872] 0.9999999999999998
Iteration	x_star	F(x_star)
319 [0.37801077 0.12555872] 0.9999999999999998
Iteration	x_star	F(x_star)
320 [0.3780

2D Rastrigin Function :
$$f(x_1, x_2)=(x_1^2-10cos(2 \pi x_1)+10) + (x_2^2-10cos(2 \pi x_2)+10) \\
-5\leq x_1,x_2\leq5
$$

In [266]:
# try f_2D_rastrigin
#random.seed(9295)
x=np.array([0,0])
domain=np.array([-5,5])
f=[lambda x: ( (x[0]**2) - 10*math.cos(2*math.pi*x[0]) + 10 ) + ( (x[1]**2) - 10*math.cos(2*math.pi*x[1]) + 10 )]
F = lambda x : 1/( 1 + sum([abs(f_(x)) for f_ in f]) )
x_star, F_x_star = spiral_dynamics_optimization(F, transformation_matrix, mat_R_ij, 20, 30, 0.9, 350, len(x), domain)
print("\nFinal value of x, F(x) is : ",x_star,",",F_x_star,"")


Init points =  20
Theta =  30
r =  0.9
iter_max =  350
dimension =  2
domain =  [-5  5]

Iteration	x_star	F(x_star)
0 [ 0.94736768 -1.04148853] 0.25894007269235725
Iteration	x_star	F(x_star)
1 [ 0.94736768 -1.04148853] 0.25894007269235725
Iteration	x_star	F(x_star)
2 [ 0.94736768 -1.04148853] 0.25894007269235725
Iteration	x_star	F(x_star)
3 [ 0.94736768 -1.04148853] 0.25894007269235725
Iteration	x_star	F(x_star)
4 [ 9.38550564e-01 -1.17613250e-04] 0.3821131998613464
Iteration	x_star	F(x_star)
5 [ 9.38550564e-01 -1.17613250e-04] 0.3821131998613464
Iteration	x_star	F(x_star)
6 [ 9.38550564e-01 -1.17613250e-04] 0.3821131998613464
Iteration	x_star	F(x_star)
7 [ 9.38550564e-01 -1.17613250e-04] 0.3821131998613464
Iteration	x_star	F(x_star)
8 [ 9.38550564e-01 -1.17613250e-04] 0.3821131998613464
Iteration	x_star	F(x_star)
9 [ 9.38550564e-01 -1.17613250e-04] 0.3821131998613464
Iteration	x_star	F(x_star)
10 [-0.03934038  1.02612868] 0.4011406680568281
Iteration	x_star	F(x_star)
11 [-0.03934038  

Iteration	x_star	F(x_star)
152 [-1.44259581e-07  1.01750576e-07] 0.9999999999938165
Iteration	x_star	F(x_star)
153 [ 4.19010766e-08 -1.54615579e-07] 0.9999999999949107
Iteration	x_star	F(x_star)
154 [9.36084601e-08 1.01934486e-07] 0.9999999999962004
Iteration	x_star	F(x_star)
155 [-1.03718317e-07  7.86960133e-08] 0.9999999999966374
Iteration	x_star	F(x_star)
156 [ 3.19928017e-08 -1.08194914e-07] 0.9999999999974722
Iteration	x_star	F(x_star)
157 [6.96874843e-08 7.88300837e-08] 0.9999999999978044
Iteration	x_star	F(x_star)
158 [-3.00776491e-08 -8.61686931e-08] 0.9999999999983462
Iteration	x_star	F(x_star)
159 [-6.97551278e-08  4.70834439e-08] 0.9999999999985949
Iteration	x_star	F(x_star)
160 [4.67643611e-08 6.08055298e-08] 0.9999999999988329
Iteration	x_star	F(x_star)
161 [-2.59644211e-08 -5.94785784e-08] 0.9999999999991651
Iteration	x_star	F(x_star)
162 [3.94914829e-08 4.87771190e-08] 0.9999999999992202
Iteration	x_star	F(x_star)
163 [-1.94188307e-08 -4.86530087e-08] 0.9999999999994564


Iteration	x_star	F(x_star)
310 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
311 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
312 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
313 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
314 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
315 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
316 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
317 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
318 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
319 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
320 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
321 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
322 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
323 [1.31734778e-09 1.33992451e-09] 1.0
Iteration	x_star	F(x_star)
324 [1.31734778e-09 1.33992451e-09]